### ISSUE TITLE
Существует более красивый вариант, как делать это

### ISSUE THREAD

**Issue by pomponchik** [fersus85/insta_bot#8]
https://github.com/fersus85/insta_bot/blob/f4e0008bab9d4f9ac35a3aa5a6660400de44765d/Insta_bot.py#L110C17-L110C17

См. https://stackoverflow.com/a/36166132/14522393

**Comment by fersus85** [comment]
Fixed
    def _is_xpath_exist(self, xpath):
        ''' inspect is exist xpath on a page '''
        return bool(self.driver.find_elements(By.XPATH, xpath))
